language: node_js

node_js:
  - "0.10"

before_install:
  - npm install npm@latest

install:
  - node_modules/.bin/npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: node_modules/.bin/gulp karma