language: node_js

node_js:
  - "0.10"

sudo: require

before_install:
  - sudo npm install -g npm@latest
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install

script: node_modules/.bin/gulp karma